services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: supchatdb
      POSTGRES_USER: supchatuser
      POSTGRES_PASSWORD: supchatpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=supchatdb;Username=supchatuser;Password=supchatpassword123
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: 